config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # root to: 'users#index'
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated :user do
    root to: 'users#index'
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index]
  resources :groups, only: %i[index show new create destroy] do
    resources :expenses, only: %i[index show new create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user: user
    can :manage, Expense, user: user

    can %i[read create], Group
    can %i[read create], Expense
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, :icon, presence: true, length: { maximum: 255 }

  def total_expenses
    expenses.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource
  def index
    @group = Group.find(params[:group_id])
    @expenses = @group.expenses.all.order(created_at: :desc)
  end

  def new
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.new
  end

  def create
    @group = Group.find(params[:group_id])
    @expense = @group.expenses.create(name: expense_params[:name], amount: expense_params[:amount],
                                      user_id: current_user.id, group_id: @group.id)
    respond_to do |format|
      if @expense.save
        format.html { redirect_to group_expenses_path(@group.id), notice: 'Transaction has been successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      return e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_with model: @expense, url: group_expenses_path, method: :post, local: true do |form| %>

    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Expense category", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :amount, "Amount", :class => "form-label" %>
      <%= form.number_field :amount, placeholder: "Amount", required: true, :class => "form-control" %>
    </div>

    <div class="p-2 text-center">
      <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>

<% end %>

app/views/expenses/index.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-chevron-left"></i></a>
    </li>
    <li>
      <h3>Transaction</h3>
    </li>
    <li>
   <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
   </nav>
<div class="p-2 text-dark-50">
  <h3><%= @group.name.capitalize %>'s transactions</h3>
  <h4>Total spent: $<%= @group.total_expenses %></h4>
</div>


<% @expenses.each do |ex| %>
  <div class="p-2">
    <div class="card p-2 bg-light">
      <div class="card-body">
        <h5 class="card-title"><%= ex.name %></h5>
        <p class="card-text">$<%= ex.amount %></p>
        <p class="card-text"><small class="text-muted"><%= ex.created_at %></small></p>
      </div>
    </div>
  </div>
<% end %>

<div class="w-100  py-1 px-1 cat-btn">
  <%= link_to "Add transaction", new_group_expense_path(@group, @expense), :class => "btn btn-outline-light" %>
</div>

app/views/expenses/new.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/" title= "back-root"><i class="fa fa-chevron-left"></i></a>
    </li>
    <li>
      <h3 class="heading fw-bold">Expenses</h3>
    </li>
    <li>
   <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
   </nav>
<h3>Add expenses</h3>
<%= render "form" %>

app/views/expenses/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/groups/_form.html.erb
<%= form_with model: @group, method: :post, local: true do |form| %>
    <div class="mb-3 p-2">
      <%= form.label :name, "Name", :class => "form-label" %>
      <%= form.text_field :name, placeholder: "Category Name", required: true, :class => "form-control" %>
    </div>

    <div class="mb-3 p-2">
      <%= form.label :icon, "Icon", :class => "form-label" %>
      <%= form.url_field :icon, placeholder: "Icon link", required: true, :class => "form-control" %>
    </div>

    <div class="p-2 text-center">
      <%= form.submit "Save", class: "btn btn-primary", disable_with: "Please wait..." %>
    </div>
<% end %>

app/views/groups/index.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/"><i class="fa fa-bars"></i></a>
    </li>
    <li>
      <h3 class="heading fw-bold">Categories</h3>
    </li>
    <li>
   <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
   </nav>
<div class="group-c px-2">
<% @groups.each do |group| %>
  <div class="card mb-3 bg-light" >
    <div class="row g-0">
      <div class="col-3 py-2 image-c">
          <%=image_tag "#{group.icon}"%>
      </div>
      <div class="col-8">
        <div class="card-body">
        <div class= "card-d">
          <%= link_to group_expenses_path(group.id) do %>
            <h5 class="card-title"><%= group.name %></h5>
          <% end %>
          <small class="card-exp"> $<%= group.total_expenses %></small>
          </div>
          <p class="card-text"><small class="text-muted"><%= group.created_at %></small></p>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<div class="w-100  py-1 px-1 cat-btn">
  <%= link_to "Add category", new_group_path, :class => "btn btn-outline-light  w-75 p-2" %>
</div>

app/views/groups/new.html.erb
<nav class="header">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    <li>
    <a href="/" title="back-root"><i class="fa fa-chevron-left"></i></a>
    </li>
    <li>
      <h3 class="heading fw-bold">Categories</h3>
    </li>
    <li>
   <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
   </nav>
<div class="d-flex p-2">
  <h3>Add your category</h3>
</div>
<%= render "form" %>

app/views/groups/show.html.erb
<h1>Expenses#show</h1>
<p>Find me in app/views/expenses/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel= "stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light">
<% if user_signed_in? %>
 <% if current_page?(root_path ) %>
       <%= link_to "BudgetApp", groups_path, class: "logo-nav light" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
 <% else  %>
       <%= link_to "<", root_path, class: "back" %>
       <%= link_to "BudgetApp", groups_path, class: "logo-nav light" %>
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "justify-content-center align-self-center btn btn-danger btn-sm sign-out" %>
 <% end %>
<% end %>
</nav>

app/views/users/index.html.erb
<div class ="first-page">
  <div class="p-3 logo-text">  
    <h1 class=" text-center py-5">BudgetApp</h1>
    <h1 class=" text-center py-5">BudgetApp</h1>
  </div>
  <div class="d-grid p-3 m-3">
    <%= link_to "Log in", new_user_session_path, :class => "btn btn-primary" %><br>
    <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-light" %>
  </div>
</div>